### ISSUE TITLE
Secure setting does not fully disable TLS connection attempts

### ISSUE THREAD

**Issue by mooninite** [Unrud/RadicaleIMAP#2]
The "imap_secure" setting is misleading. You've programmed it to always attempt a TLS connection first, and only failover to a non-encrypted connection after an encrypted attempt fails. The exception does not always catch all errors. Example: When the CA is not trusted (or a self-signed cert is used) the code fails completely and an unencrypted connection is never attempted.

Would you accept a pull request to only attempt TLS if "imap_secure" is set to true?

**Comment by r3c** [comment]
Same issue here, using "imap_secure = False" option currently can't work with self-signed certificates. I'm trying to migrate to Radicale 2.x but am missing imap authentication and was redirected here from https://github.com/Kozea/Radicale/issues/643.

Is this plugin still supported, and would you consider adding support for non-trusted TLS connections (or accept a PR doing so)?
